@echo off
REM Generated by trunk tool 'prettier'
set PATH=C:\Users\polas\AppData\Local\trunk\tools\prettier\3.8.3-9c9474669329ea0930935313511759e9/node_modules/.bin;C:\Users\polas\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c/bin;C:\Users\polas\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c;C:\Users\polas\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\polas\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set NODE_PATH=C:\Users\polas\AppData\Local\trunk\tools\prettier\3.8.3-9c9474669329ea0930935313511759e9/node_modules

start /w /b prettier %*
