@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\polas\AppData\Local\trunk\tools\trufflehog\3.95.3-adcde8e3d4daebe5e283de063acff9f6;C:\Users\polas\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\polas\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
